swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: this is a description with tags. <a href="https://www.evildojo.com" onclick="alert``">www.evildojo.com</a> Unicode: \u0064\u0065
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      parameters:
          - description: testing hello world
      responses:
        '200':
          description: No response was specified <b>testing bold tag</b> <i>testing italics</i> 
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
