swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: this is a description with tags.  
  version: production
basePath: /
produces:
  - text/html
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      parameters:
          - description: testing hello world <a href="https://www.evildojo.com">www.evildojo.com</a> Unicode: \u0064\u0065

      responses:
        '200':
          description: No response was specified <b>testing bold tag</b> <i>testing italics</i> 
      tags:
        - accounts<b>bold</b>
      operationId: findAccounts
      summary: Finds all accounts
